apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mimir.resourceName" (dict "ctx" . "component" "runtime") }}
  labels:
    {{- include "mimir.labels" (dict "ctx" .) | nindent 4 }}
  namespace: {{ include "mimir.namespace" . | quote }}
data:
  runtime.yaml: |
    {{ tpl (toYaml .Values.runtimeConfig) . | nindent 4 }}
